var makaUpload = require('./makaUpload');
var rabUpload = require('./rabUpload');
var updateRabbit = require('./updateRabbit');
var mydb = require('./mydb');
var cryptoTest = require('./cryptoTest');
var eqxCrawler = require('./eqxCrawler');
var uploadTest = require('./uploadTest');
var convertpath = require('./convertpath');
// updateRabbit();
// makaUpload();
rabUpload();
// mydb();
// cryptoTest();
// convertpath();
// eqxCrawler();
// uploadTest();