var makaUpload = require('./makaUpload');
var rabUpload = require('./rabUpload');
var updateRabbit = require('./updateRabbit');
var mydb = require('./mydb');
var cryptoTest = require('./cryptoTest');
// var convertpath = require('./convertpath');
// updateRabbit();
// makaUpload();
// rabUpload();
mydb();
// cryptoTest();
// convertpath();
